modLoader="javafml"
loaderVersion="[2,)"
license="Academic Free License v3.0"

[[mods]]
modId="minato_furniture"
version="2.1.2"
displayName="Minato's Furniture"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="midok, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.minato_furniture]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.minato_furniture]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration