
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.minatosfurniture.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.minatosfurniture.block.ToiletOpenBlock;
import net.mcreator.minatosfurniture.block.ToiletBlock;
import net.mcreator.minatosfurniture.block.TVOnBlock;
import net.mcreator.minatosfurniture.block.TVBlock;
import net.mcreator.minatosfurniture.block.SpruceVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.SpruceTableBlock;
import net.mcreator.minatosfurniture.block.SpruceChairBlock;
import net.mcreator.minatosfurniture.block.SpruceBellBlock;
import net.mcreator.minatosfurniture.block.SmoothStoneVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.SmoothStoneTableBlock;
import net.mcreator.minatosfurniture.block.SmoothStoneChairBlock;
import net.mcreator.minatosfurniture.block.SmoothStoneBellBlock;
import net.mcreator.minatosfurniture.block.ShowerHeadOnBlock;
import net.mcreator.minatosfurniture.block.ShowerHeadBlock;
import net.mcreator.minatosfurniture.block.ShavedIceMachineInIceBlock;
import net.mcreator.minatosfurniture.block.ShavedIceMachineBlock;
import net.mcreator.minatosfurniture.block.ShavedIceMachine7Block;
import net.mcreator.minatosfurniture.block.ShavedIceMachine6Block;
import net.mcreator.minatosfurniture.block.ShavedIceMachine5Block;
import net.mcreator.minatosfurniture.block.ShavedIceMachine4Block;
import net.mcreator.minatosfurniture.block.ShavedIceMachine3Block;
import net.mcreator.minatosfurniture.block.ShavedIceMachine2Block;
import net.mcreator.minatosfurniture.block.ShavedIceMachine1Block;
import net.mcreator.minatosfurniture.block.Refrigerator2Block;
import net.mcreator.minatosfurniture.block.Refrigerator1Block;
import net.mcreator.minatosfurniture.block.PolishedGraniteVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.PolishedGraniteTableBlock;
import net.mcreator.minatosfurniture.block.PolishedGraniteChairBlock;
import net.mcreator.minatosfurniture.block.PolishedGraniteBellBlock;
import net.mcreator.minatosfurniture.block.PolishedDioriteVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.PolishedDioriteTableBlock;
import net.mcreator.minatosfurniture.block.PolishedDioriteChairBlock;
import net.mcreator.minatosfurniture.block.PolishedDioriteBellBlock;
import net.mcreator.minatosfurniture.block.PolishedAndsiteChairBlock;
import net.mcreator.minatosfurniture.block.PolishedAndesiteVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.PolishedAndesiteTableBlock;
import net.mcreator.minatosfurniture.block.PolishedAndesiteBellBlock;
import net.mcreator.minatosfurniture.block.OakTableBlock;
import net.mcreator.minatosfurniture.block.OakChairBlock;
import net.mcreator.minatosfurniture.block.OakBookshelfBlock;
import net.mcreator.minatosfurniture.block.OakBellBlock;
import net.mcreator.minatosfurniture.block.MangroveVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.MangroveTableBlock;
import net.mcreator.minatosfurniture.block.MangroveChairBlock;
import net.mcreator.minatosfurniture.block.MangroveBellBlock;
import net.mcreator.minatosfurniture.block.JungleVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.JungleTableBlock;
import net.mcreator.minatosfurniture.block.JungleChairBlock;
import net.mcreator.minatosfurniture.block.JungleBellBlock;
import net.mcreator.minatosfurniture.block.IngredientsCutterBlock;
import net.mcreator.minatosfurniture.block.HotSpringBlock;
import net.mcreator.minatosfurniture.block.HighHeatOvenBlock;
import net.mcreator.minatosfurniture.block.FanBlockBlock;
import net.mcreator.minatosfurniture.block.DarkOakVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.DarkOakTableBlock;
import net.mcreator.minatosfurniture.block.DarkOakChairBlock;
import net.mcreator.minatosfurniture.block.DarkOakBellBlock;
import net.mcreator.minatosfurniture.block.ConnectedSpruceTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedSmoothStoneTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedPolishedGraniteTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedPolishedDioriteTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedPolishedAndesiteTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedOakTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedMangroveTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedJungleTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedDarkOakTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedCherryTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedBirchTableBlock;
import net.mcreator.minatosfurniture.block.ConnectedAcaciaTableBlock;
import net.mcreator.minatosfurniture.block.CherryVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.CherryTableBlock;
import net.mcreator.minatosfurniture.block.CherryChairBlock;
import net.mcreator.minatosfurniture.block.CherryBellBlock;
import net.mcreator.minatosfurniture.block.BirchVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.BirchTableBlock;
import net.mcreator.minatosfurniture.block.BirchChairBlock;
import net.mcreator.minatosfurniture.block.BirchBellBlock;
import net.mcreator.minatosfurniture.block.Bath3Block;
import net.mcreator.minatosfurniture.block.Bath2Block;
import net.mcreator.minatosfurniture.block.Bath1Block;
import net.mcreator.minatosfurniture.block.AcaciaVerticalBookshelfBlock;
import net.mcreator.minatosfurniture.block.AcaciaTableBlock;
import net.mcreator.minatosfurniture.block.AcaciaChairBlock;
import net.mcreator.minatosfurniture.block.AcaciaBellBlock;
import net.mcreator.minatosfurniture.MinatoFurnitureMod;

public class MinatoFurnitureModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, MinatoFurnitureMod.MODID);
	public static final RegistryObject<Block> OAK_CHAIR = REGISTRY.register("oak_chair", () -> new OakChairBlock());
	public static final RegistryObject<Block> SPRUCE_CHAIR = REGISTRY.register("spruce_chair", () -> new SpruceChairBlock());
	public static final RegistryObject<Block> BIRCH_CHAIR = REGISTRY.register("birch_chair", () -> new BirchChairBlock());
	public static final RegistryObject<Block> JUNGLE_CHAIR = REGISTRY.register("jungle_chair", () -> new JungleChairBlock());
	public static final RegistryObject<Block> ACACIA_CHAIR = REGISTRY.register("acacia_chair", () -> new AcaciaChairBlock());
	public static final RegistryObject<Block> DARK_OAK_CHAIR = REGISTRY.register("dark_oak_chair", () -> new DarkOakChairBlock());
	public static final RegistryObject<Block> SMOOTH_STONE_CHAIR = REGISTRY.register("smooth_stone_chair", () -> new SmoothStoneChairBlock());
	public static final RegistryObject<Block> POLISHED_GRANITE_CHAIR = REGISTRY.register("polished_granite_chair", () -> new PolishedGraniteChairBlock());
	public static final RegistryObject<Block> POLISHED_DIORITE_CHAIR = REGISTRY.register("polished_diorite_chair", () -> new PolishedDioriteChairBlock());
	public static final RegistryObject<Block> POLISHED_ANDESITE_CHAIR = REGISTRY.register("polished_andesite_chair", () -> new PolishedAndsiteChairBlock());
	public static final RegistryObject<Block> BATH_1 = REGISTRY.register("bath_1", () -> new Bath1Block());
	public static final RegistryObject<Block> BATH_2 = REGISTRY.register("bath_2", () -> new Bath2Block());
	public static final RegistryObject<Block> BATH_3 = REGISTRY.register("bath_3", () -> new Bath3Block());
	public static final RegistryObject<Block> OAK_TABLE = REGISTRY.register("oak_table", () -> new OakTableBlock());
	public static final RegistryObject<Block> SPRUCE_TABLE = REGISTRY.register("spruce_table", () -> new SpruceTableBlock());
	public static final RegistryObject<Block> BIRCH_TABLE = REGISTRY.register("birch_table", () -> new BirchTableBlock());
	public static final RegistryObject<Block> JUNGLE_TABLE = REGISTRY.register("jungle_table", () -> new JungleTableBlock());
	public static final RegistryObject<Block> ACACIA_TABLE = REGISTRY.register("acacia_table", () -> new AcaciaTableBlock());
	public static final RegistryObject<Block> DARK_OAK_TABLE = REGISTRY.register("dark_oak_table", () -> new DarkOakTableBlock());
	public static final RegistryObject<Block> SMOOTH_STONE_TABLE = REGISTRY.register("smooth_stone_table", () -> new SmoothStoneTableBlock());
	public static final RegistryObject<Block> POLISHED_GRANITE_TABLE = REGISTRY.register("polished_granite_table", () -> new PolishedGraniteTableBlock());
	public static final RegistryObject<Block> POLISHED_DIORITE_TABLE = REGISTRY.register("polished_diorite_table", () -> new PolishedDioriteTableBlock());
	public static final RegistryObject<Block> POLISHED_ANDESITE_TABLE = REGISTRY.register("polished_andesite_table", () -> new PolishedAndesiteTableBlock());
	public static final RegistryObject<Block> REFRIGERATOR_1 = REGISTRY.register("refrigerator_1", () -> new Refrigerator1Block());
	public static final RegistryObject<Block> REFRIGERATOR_2 = REGISTRY.register("refrigerator_2", () -> new Refrigerator2Block());
	public static final RegistryObject<Block> INGREDIENTS_CUTTER = REGISTRY.register("ingredients_cutter", () -> new IngredientsCutterBlock());
	public static final RegistryObject<Block> HOT_SPRING = REGISTRY.register("hot_spring", () -> new HotSpringBlock());
	public static final RegistryObject<Block> SHOWER_HEAD = REGISTRY.register("shower_head", () -> new ShowerHeadBlock());
	public static final RegistryObject<Block> SHOWER_HEAD_ON = REGISTRY.register("shower_head_on", () -> new ShowerHeadOnBlock());
	public static final RegistryObject<Block> SHAVED_ICE_MACHINE = REGISTRY.register("shaved_ice_machine", () -> new ShavedIceMachineBlock());
	public static final RegistryObject<Block> SHAVED_ICE_MACHINE_1 = REGISTRY.register("shaved_ice_machine_1", () -> new ShavedIceMachine1Block());
	public static final RegistryObject<Block> SHAVED_ICE_MACHINE_2 = REGISTRY.register("shaved_ice_machine_2", () -> new ShavedIceMachine2Block());
	public static final RegistryObject<Block> SHAVED_ICE_MACHINE_3 = REGISTRY.register("shaved_ice_machine_3", () -> new ShavedIceMachine3Block());
	public static final RegistryObject<Block> SHAVED_ICE_MACHINE_4 = REGISTRY.register("shaved_ice_machine_4", () -> new ShavedIceMachine4Block());
	public static final RegistryObject<Block> SHAVED_ICE_MACHINE_5 = REGISTRY.register("shaved_ice_machine_5", () -> new ShavedIceMachine5Block());
	public static final RegistryObject<Block> SHAVED_ICE_MACHINE_6 = REGISTRY.register("shaved_ice_machine_6", () -> new ShavedIceMachine6Block());
	public static final RegistryObject<Block> SHAVED_ICE_MACHINE_7 = REGISTRY.register("shaved_ice_machine_7", () -> new ShavedIceMachine7Block());
	public static final RegistryObject<Block> SHAVED_ICE_MACHINE_IN_ICE = REGISTRY.register("shaved_ice_machine_in_ice", () -> new ShavedIceMachineInIceBlock());
	public static final RegistryObject<Block> TV = REGISTRY.register("tv", () -> new TVBlock());
	public static final RegistryObject<Block> TV_ON = REGISTRY.register("tv_on", () -> new TVOnBlock());
	public static final RegistryObject<Block> FAN_BLOCK = REGISTRY.register("fan_block", () -> new FanBlockBlock());
	public static final RegistryObject<Block> HIGH_HEAT_OVEN = REGISTRY.register("high_heat_oven", () -> new HighHeatOvenBlock());
	public static final RegistryObject<Block> TOILET_OPEN = REGISTRY.register("toilet_open", () -> new ToiletOpenBlock());
	public static final RegistryObject<Block> TOILET = REGISTRY.register("toilet", () -> new ToiletBlock());
	public static final RegistryObject<Block> OAK_VERTICAL_BOOKSHELF = REGISTRY.register("oak_vertical_bookshelf", () -> new OakBookshelfBlock());
	public static final RegistryObject<Block> SPRUCE_VERTICAL_BOOKSHELF = REGISTRY.register("spruce_vertical_bookshelf", () -> new SpruceVerticalBookshelfBlock());
	public static final RegistryObject<Block> BIRCH_VERTICAL_BOOKSHELF = REGISTRY.register("birch_vertical_bookshelf", () -> new BirchVerticalBookshelfBlock());
	public static final RegistryObject<Block> MANGROVE_CHAIR = REGISTRY.register("mangrove_chair", () -> new MangroveChairBlock());
	public static final RegistryObject<Block> MANGROVE_TABLE = REGISTRY.register("mangrove_table", () -> new MangroveTableBlock());
	public static final RegistryObject<Block> CHERRY_CHAIR = REGISTRY.register("cherry_chair", () -> new CherryChairBlock());
	public static final RegistryObject<Block> CHERRY_TABLE = REGISTRY.register("cherry_table", () -> new CherryTableBlock());
	public static final RegistryObject<Block> JUNGLE_VERTICAL_BOOKSHELF = REGISTRY.register("jungle_vertical_bookshelf", () -> new JungleVerticalBookshelfBlock());
	public static final RegistryObject<Block> ACACIA_VERTICAL_BOOKSHELF = REGISTRY.register("acacia_vertical_bookshelf", () -> new AcaciaVerticalBookshelfBlock());
	public static final RegistryObject<Block> DARK_OAK_VERTICAL_BOOKSHELF = REGISTRY.register("dark_oak_vertical_bookshelf", () -> new DarkOakVerticalBookshelfBlock());
	public static final RegistryObject<Block> MANGROVE_VERTICAL_BOOKSHELF = REGISTRY.register("mangrove_vertical_bookshelf", () -> new MangroveVerticalBookshelfBlock());
	public static final RegistryObject<Block> CHERRY_VERTICAL_BOOKSHELF = REGISTRY.register("cherry_vertical_bookshelf", () -> new CherryVerticalBookshelfBlock());
	public static final RegistryObject<Block> SMOOTH_STONE_VERTICAL_BOOKSHELF = REGISTRY.register("smooth_stone_vertical_bookshelf", () -> new SmoothStoneVerticalBookshelfBlock());
	public static final RegistryObject<Block> POLISHED_GRANITE_VERTICAL_BOOKSHELF = REGISTRY.register("polished_granite_vertical_bookshelf", () -> new PolishedGraniteVerticalBookshelfBlock());
	public static final RegistryObject<Block> POLISHED_DIORITE_VERTICAL_BOOKSHELF = REGISTRY.register("polished_diorite_vertical_bookshelf", () -> new PolishedDioriteVerticalBookshelfBlock());
	public static final RegistryObject<Block> POLISHED_ANDESITE_VERTICAL_BOOKSHELF = REGISTRY.register("polished_andesite_vertical_bookshelf", () -> new PolishedAndesiteVerticalBookshelfBlock());
	public static final RegistryObject<Block> CONNECTED_OAK_TABLE = REGISTRY.register("connected_oak_table", () -> new ConnectedOakTableBlock());
	public static final RegistryObject<Block> CONNECTED_SPRUCE_TABLE = REGISTRY.register("connected_spruce_table", () -> new ConnectedSpruceTableBlock());
	public static final RegistryObject<Block> CONNECTED_BIRCH_TABLE = REGISTRY.register("connected_birch_table", () -> new ConnectedBirchTableBlock());
	public static final RegistryObject<Block> CONNECTED_JUNGLE_TABLE = REGISTRY.register("connected_jungle_table", () -> new ConnectedJungleTableBlock());
	public static final RegistryObject<Block> CONNECTED_ACACIA_TABLE = REGISTRY.register("connected_acacia_table", () -> new ConnectedAcaciaTableBlock());
	public static final RegistryObject<Block> CONNECTED_DARK_OAK_TABLE = REGISTRY.register("connected_dark_oak_table", () -> new ConnectedDarkOakTableBlock());
	public static final RegistryObject<Block> CONNECTED_SMOOTH_STONE_TABLE = REGISTRY.register("connected_smooth_stone_table", () -> new ConnectedSmoothStoneTableBlock());
	public static final RegistryObject<Block> CONNECTED_POLISHED_GRANITE_TABLE = REGISTRY.register("connected_polished_granite_table", () -> new ConnectedPolishedGraniteTableBlock());
	public static final RegistryObject<Block> CONNECTED_POLISHED_DIORITE_TABLE = REGISTRY.register("connected_polished_diorite_table", () -> new ConnectedPolishedDioriteTableBlock());
	public static final RegistryObject<Block> CONNECTED_POLISHED_ANDESITE_TABLE = REGISTRY.register("connected_polished_andesite_table", () -> new ConnectedPolishedAndesiteTableBlock());
	public static final RegistryObject<Block> CONNECTED_MANGROVE_TABLE = REGISTRY.register("connected_mangrove_table", () -> new ConnectedMangroveTableBlock());
	public static final RegistryObject<Block> CONNECTED_CHERRY_TABLE = REGISTRY.register("connected_cherry_table", () -> new ConnectedCherryTableBlock());
	public static final RegistryObject<Block> OAK_BELL = REGISTRY.register("oak_bell", () -> new OakBellBlock());
	public static final RegistryObject<Block> SPRUCE_BELL = REGISTRY.register("spruce_bell", () -> new SpruceBellBlock());
	public static final RegistryObject<Block> BIRCH_BELL = REGISTRY.register("birch_bell", () -> new BirchBellBlock());
	public static final RegistryObject<Block> JUNGLE_BELL = REGISTRY.register("jungle_bell", () -> new JungleBellBlock());
	public static final RegistryObject<Block> ACACIA_BELL = REGISTRY.register("acacia_bell", () -> new AcaciaBellBlock());
	public static final RegistryObject<Block> DARK_OAK_BELL = REGISTRY.register("dark_oak_bell", () -> new DarkOakBellBlock());
	public static final RegistryObject<Block> SMOOTH_STONE_BELL = REGISTRY.register("smooth_stone_bell", () -> new SmoothStoneBellBlock());
	public static final RegistryObject<Block> POLISHED_GRANITE_BELL = REGISTRY.register("polished_granite_bell", () -> new PolishedGraniteBellBlock());
	public static final RegistryObject<Block> POLISHED_DIORITE_BELL = REGISTRY.register("polished_diorite_bell", () -> new PolishedDioriteBellBlock());
	public static final RegistryObject<Block> POLISHED_ANDESITE_BELL = REGISTRY.register("polished_andesite_bell", () -> new PolishedAndesiteBellBlock());
	public static final RegistryObject<Block> CHERRY_BELL = REGISTRY.register("cherry_bell", () -> new CherryBellBlock());
	public static final RegistryObject<Block> MANGROVE_BELL = REGISTRY.register("mangrove_bell", () -> new MangroveBellBlock());
	// Start of user code block custom blocks
	// End of user code block custom blocks
}
